# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='budget',
            field=models.CharField(choices=[('Cheap', '$'), ('Affordable', '$$'), ('Expensive', '$$$'), ('Very_Expensive', '$$$$')], default='Affordable', max_length=15),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
